repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: black
        name: black
        entry: ./.venv/bin/black
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: ./.venv/bin/flake8
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: ./.venv/bin/mypy
        language: system
        types: [python]
        args: [--no-warn-no-return, --ignore-missing-imports] # Example mypy args, adjust as needed
      - id: isort
        name: isort
        entry: ./.venv/bin/isort
        language: system
        types: [python]
      - id: pylint
        name: pylint
        entry: ./.venv/bin/pylint
        language: system
        args: ["--rcfile=.pylintrc"]
        types: [python]
      - id: pytest
        name: pytest
        entry: ./.venv/bin/pytest
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
        stages: [commit]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5 # Use a specific version
    hooks:
      - id: shellcheck
